### ISSUE TITLE
【教程】Docker版部署方法

### ISSUE THREAD

**Issue by wudifeixue** [CikeyQi/QQsign_docs#11]
# Docker版部署方法
## 一条命令部署
```bash
sudo docker run -d -e TXLIB_VERSION=8.9.90 -p 8080:8080 --restart=always cikeyqi/unidbg-fetch-qsign-docker
```

## Docker Compose方法部署
```yaml
version: '3'
services:
  unidbg-service:
    image: cikeyqi/unidbg-fetch-qsign-docker
    environment:
      - TXLIB_VERSION=8.9.90
    ports:
      - "8080:8080"
    restart: always
```
将这个内容保存为 `docker-compose.yml` 文件。然后，在该文件所在目录下运行 `docker-compose up -d` 命令来启动服务。这样，容器就会以配置文件中定义的方式启动。

## 注意事项
1. TXLIB_VERSION默认使用的是**8.9.96**，请**务必**改成你需要的版本，优先低一点比较好
2. 这个只支持x86的构架，ARM并不能通过测试
3. 如果安卓版本(上面的TXLIB_VERSION)不一致，你要先删除device.json
4. 如果你用的喵喵云崽记得改签名服务器设置(bot/config/config/bot.yaml)，TRSS记得改cqhttp的签名地址设置(我不熟悉看文档这里`config.yml`这里）此Docker默认地址是`http://127.0.0.1:8080/sign?key=114514`
